apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: jaeger-all-in-one
  name: jaeger-all-in-one
spec:
  containers:
  - image: jaegertracing/all-in-one:1.6
    name: jaeger-all-in-one
    ports:
    - containerPort: 5775
      protocol: UDP
    - containerPort: 6831
      protocol: UDP
    - containerPort: 6832
      protocol: UDP
    - containerPort: 5778
    - containerPort: 14267
    - containerPort: 14268
    - containerPort: 14269
    - containerPort: 16686
    - containerPort: 16687
    - containerPort: 9411
    resources: {}
  restartPolicy: OnFailure
status: {}
