apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: kafka
  name: kafka
spec:
  containers:
  - env:
    - name: KAFKA_ADVERTISED_LISTENERS
      value: PLAINTEXT://localhost:9092
    - name: KAFKA_BROKER_ID
      value: "1"
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_ZOOKEEPER_CONNECT
      value: zookeeper:2181
    image: confluentinc/cp-kafka:5.0.0-2
    name: kafka
    ports:
    - containerPort: 9092
    resources: {}
  restartPolicy: OnFailure
status: {}
